name: 'Parse Git Version'
description: 'Parses the `git describe` version.'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - id: show-version
      run: |
        DESCRIBE_VERSION=$(git describe --tags --long --dirty)
        echo DESCRIBE_VERSION
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
    - run: ${{ github.action_path }}/goodbye.sh
      shell: bash
