name: 'Parse Git Version'
description: 'Parses the `git describe` version.'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - id: show-version
      run: |
        source ${{ github.action_path }}/parse_version.sh
        echo "${GIT_DESCRIBE_VERSION}"
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
