name: 'Parse Git Version'
description: 'Parses the `git describe` version.'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}

  major:
    description: "The major version number"
    value: ${{ steps.parse-version.outputs.major }}
  minor:
    description: "The minor version number"
    value: ${{ steps.parse-version.outputs.minor }}
  patch:
    description: "The patch version number"
    value: ${{ steps.parse-version.outputs.patch }}
runs:
  using: "composite"
  steps:
    - id: parse-version
      run: |
        source ${{ github.action_path }}/parse_version.sh
        echo "::set-output name=major::$(echo $MAJOR)"
      shell: bash
