name: Cleanup Images

on:
  # https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#registry_package
  registry_package:
  # https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:

jobs:
  delete-untagged-images:
    uses: energy-quants/.github/.github/workflows/cleanup-images.yml@main
    with:
      org: energy-quants
      repo: mambaforge
      image: mambaforge
    secrets:
      ghcr_token: ${{ secrets.GHCR_TOKEN }}
