name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Show Environment
        run: env | sort
      - name: Show GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Parse Version
        id: parse_version
        uses: ./.github/actions/parse-git-version
      - name: Build Container Image
        shell: bash
        env:
          VERSION: ${{ steps.parse_version.outputs.version }}
          SCRIPTS_DIR: "${{ github.workspace }}/bootstrap/linux/mambaforge/"
          GITHUB_REPO: ${{ github.repository }}
        run: |
          echo $(buildah --version)
          source ${{ github.workspace }}/build/images/mambaforge.sh
      - name: Publish Image
        shell: bash
        run: |
          set -euox pipefail
          IFS='/' read owner repo <<< ${{ github.repository }}
          registry="ghcr.io"
          image_name="${registry}/${owner}/${repo}/mambaforge"
          if [[ "${{ github.event_name }}" == "pull_request_target" ]]; then
            image_name="${image_name}/pr-${{ github.event.number }}"
          fi
          image_tag="latest"
          buildah tag localhost/mambaforge "${image_name}:${image_tag}"
          buildah images
          buildah login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
          # https://github.community/t/package-container-linking-via-label-not-working/176401/12
          buildah push --format v2s2 "${image_name}:${image_tag}"


# curl -fsSL -H "Authorization: token ${GITHUB_TOKEN}" 'https://api.github.com/orgs/energy-quants/packages/container/mambaforge%2Fmambaforge%2Fpr-2'